on:
    workflow_call:

jobs:
    release-notes:
        name:    release pushed tag
        runs-on: ubuntu-latest
        if:      ${{ startsWith(github.ref, 'refs/tags/xlibre-') }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: X11Libre/action-build-driver/release@v0.0.2
